### PR TITLE
assembly benchmark validator added 

### PR DESCRIPTION
**Pull request by pbelmann**
see #12

### CODE REVIEW

**Comment by pbelmann** [comment]
`biobox verify assembler_benchmark bioboxes/quast --task=default` should pass the tests

**Comment by michaelbarton** [comment]
Thank you for this PR Peter. Could you add a feature to [the verification file](https://github.com/bioboxes/command-line-interface/blob/master/features/verify.feature)? This will ensure this is non accidentally broken in future versions.

**Comment by michaelbarton** [comment]
You could update line 6 so that it is something like:

```
biobox verify <type> <image> <args>
```

**Comment by pbelmann** [comment]
ok

**Pull request merged**
